CS490/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views


app_name = 'app'  # here for namespacing of urls.

urlpatterns = [
    path('', views.index, name="index"),
    path('test', views.test_page, name="testpage"),

    # sign up
    path('signup', views.user_signup, name="signup"),
    path('signup/success', views.user_signup_success, name="signup-success"),

    # login logout
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

    # feed
    path('feed', views.feed, name="feed"),
    path('post/<int:post>', views.user_post, name="user_post"),

    # getfeed
    path('user/search', views.user_search, name="user_search"),
    path('user/feed', views.user_feed, name="user_feed"),

    # profile
    path('profile', views.profile, name="profile"),
    path('profile/edit', views.edit_profile, name="profile_edit"),
    path('user/<str:username>', views.user_profile, name="user_profile"),

    # messages
    path('message', views.msgthread, name="message"),
    path('message/search', views.msg_user, name="msguser"),
    path('message/<str:username>/', views.ThreadView.as_view(), name='chat_room'),

    #follow
    path('follow/<str:username>/', views.follow, name='follow'),

    #like
    path('post/like', views.like_ajax, name='like_ajax'),

    #password change
    path('password', views.change_password, name='password_change'),
]

app/models.py
from os import listdir, path
from cloudinary import api
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.core.exceptions import ValidationError
from django.db.models.query_utils import Q
from CS490.settings import MEDIA_DIR
from app.validators import MinAgeValidator
from cloudinary.models import CloudinaryField

import random
# Create your models here.


def random_img():
    default_img = MEDIA_DIR.joinpath('default')
    rand = random.choice(listdir(default_img))
    print(path.join(default_img, rand))
    return path.join('default', rand)


class Follower(models.Model):
    follower = models.ForeignKey(
        User, on_delete=CASCADE, related_name='following')
    following = models.ForeignKey(
        User, on_delete=CASCADE, related_name='followers')

    class Meta:
        unique_together = ('follower', 'following')

    def clean(self):
        super().clean()
        if self.follower == self.following:
            raise ValidationError('You can not follow yourself')

    def __str__(self):
        return u'%s ->follows-> %s' % (self.follower, self.following)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    admin = models.BooleanField(default=False)
    # additional

    date_of_birth = models.DateField(validators=[MinAgeValidator(18)])
    profile_pic = CloudinaryField(allowed_formats=['jpg', 'png', 'gif'], folder="profile_pics/", default=random_img)
    user_bio = models.TextField(max_length=256, blank=True)

    def __str__(self):
        return self.user.username

class UserAnnoucement(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    announcement = models.TextField(max_length=280)
    image = CloudinaryField(
        allowed_formats=['jpg', 'png'], folder="user_files/", blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.user.username + "-->" + self.announcement


class UserComment(models.Model):
    post = models.ForeignKey(UserAnnoucement, on_delete=CASCADE)
    user = models.ForeignKey(User, on_delete=CASCADE)
    comment = models.TextField(max_length=280)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.user.username + "  --Commented on--> " + self.post.announcement

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    post = models.ForeignKey(UserAnnoucement, on_delete=CASCADE)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.user.username + "  --Liked on--> " + self.post.announcement

class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(User, on_delete=CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(User, on_delete=CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def clean(self):
        super().clean()
        if self.first == self.second:
            raise ValidationError('You can not message yourself')

    def __str__(self):
        return u'%s <- nessage thread -> %s' % (self.first, self.second)


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=SET_NULL)
    user        = models.ForeignKey(User, verbose_name='sender', on_delete=CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

app/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.forms.widgets import FileInput
from app.models import UserAnnoucement, UserComment, UserProfile

class UsernameField(forms.CharField):
    def to_python(self, value):
        return value.lower()
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)
    username = UsernameField(max_length=15, min_length=3, required=True, help_text="Username must be between 3 - 15 characters and can contain '_'. ",validators=[
        RegexValidator(
            regex='^(?=.{3,15}$)(?!.*[_]{2})[a-zA-Z0-9_]+$',
            message='Username is invalid!',
            code='invalid_username'
        ),
    ])
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control','aria-describedby':'basic-addon1'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')

        if User.objects.filter(username=username.lower()).exists():
            raise ValidationError("Username already in use.")
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already in use.")
        return self.cleaned_data

    
class UserProfileDOBForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('date_of_birth',)
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control','type':"date"})


class UserProfileDetailForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic','user_bio')
        widgets = {
            'profile_pic': FileInput(attrs={'name':'image', 'accept': 'image/*'})
        }


class UserInfoDetailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control','placeholder':'Username'})
        self.fields['password'].widget.attrs.update({'class': 'form-control','placeholder':'Password'})

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username').lower()
        print(username)
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            
            if not user:
                raise forms.ValidationError('Invalid username or password.')
            if not user.is_active:
                raise forms.ValidationError('User status is currently inactive')

        return super(UserLoginForm,self).clean(*args, **kwargs)

class UserTweet(forms.ModelForm):
    class Meta:
        model = UserAnnoucement
        fields = ('announcement','image')


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = UserComment
        fields = ('comment',)

class ComposeMSGForm(forms.Form):
    message = forms.CharField(max_length=280)

templates/app/base.html
<!--Template/base.html-->
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %}</title>
    <meta name="description" content="{% block description %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'boxicons/css/boxicons.min.css' %}" type="text/css" media="screen">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block vendor %} {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

<footer>
    {% include "app/partials/footer.html"%}
</footer>
</html>

templates/app/feed.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Feed{% endblock %}
{% block description %}User feed consisting of announcement, photos, documentation, and etc.{% endblock %}
{% block vendor %}
<script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/feed.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/feed.css' %}" type="text/css" media="screen">
{% endblock %}
{% block content %}
{% include "app/partials/navbar.html" with user=user active_tab='home'%}
<section id="feed" class="f-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 col-sm-10 col-lg-8 col-lg-6">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control announcementform" name="announcement" rows="3" maxlength="280"
                            required="" id="{{announcement_form.announcement.id_for_label}}"
                            spellcheck="false"></textarea>
                    </div>
                    <div class="row">
                        <div class="col img_upload">
                            <input type="file" name="image" accept="image/*" id="{{announcement_form.image.id_for_label}}">
                        </div>
                        <div class="col">
                            <div class="form-group text-right">
                                <button type="submit" onclick="get_feed()"class="btn btn-outline-primary">Post</button>
                            </div>
                        </div>
                    </div>
                    
                </form>
                <div id="feed-content">
                    {% include "app/partials/user_feed.html" %}
                </div>
            </div>
            <div id="searchfield" class="col-sm-4 col-md-4 col-lg-4">
                <input id="user-input" class="form-control" type="search" placeholder="Search" aria-label="Search">
                <div id="search-content">
                    {% include "app/partials/user_search.html" %}
                </div>    
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Social Media App{% endblock %}
{% block description %}Social Media App created for CS:490 @NJIT{% endblock %}
{% block vendor %} 
<link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css" media="screen">
{% endblock %}
{% block content %}
<section id="landing" class="d-flex flex-column justify-content-center" >
  <div class="container" >
    <div class="logo">
      <img src="{% static "assets/logo/banner.png"%}" alt=".." class="banner">
    </div>
      <!-- <h1>Social Media App <br><span>Rutgers-Newark & NJIT</span></h1> -->
      <p class="p-large">App is running on Django 3.1.2</p>
      <div class="col">
        <a href="{% url 'app:signup' %}" class="btn bt1 btn-outline-primary">Sign up</a>
        <a href="{% url 'app:login' %}" class="btn bt2 btn-outline-primary">Login</a>
      </div>
  </div>
</section>
{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block description %}Login to your account to gain access to application{% endblock %}
{% block content %}
{% block vendor %} 
<link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% endblock %}
<section id="login" class="f-section d-flex flex-column justify-content-center">
    <div class="container cube-trans">
        <div class="row justify-content-center">
            <h1 class="title">Login</h1>
        </div>
        <form method="POST" class="row signupform justify-content-center">
            <div class="col-10 col-md-7 col-lg-5">
                {% csrf_token %}
                {% if login_form.errors %}
                    {% for field in login_form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in login_form.non_field_errors %}
                        <div class="alert alert-warning" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="form-group">
                    {{login_form.username}}
                </div>
                <div class="form-group">
                    {{login_form.password}}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn bt btn-outline-primary col-12">Login</button>
                </div>
                <div class="row signup justify-content-center">
                    <p>Don't have an account? <a href="{% url 'app:signup' %}">Sign up</a></p>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

templates/app/navbar.html
<nav id='navbar' class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
        aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:feed' %}">Home</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
                <a class="nav-link waves-effect waves-light">1
                    <i class="fas fa-envelope"></i>
                </a>
            </li> -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  {{user.first_name}} {{user.last_name}}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item disabled" href="#">My Profile</a>
                  <a class="dropdown-item disabled" href="#">Settings</a>
                  <a class="dropdown-item" href="{% url 'app:logout' %}">Log out</a>
                </div>
              </li>
        </ul>
    </div>
</nav>

templates/app/profile.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}{{profile_data.user.first_name}} {{profile_data.user.last_name}} - @{{profile_data.user.username}}{% endblock %}
{% block description %}User profile containing feed and personal info.{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
{% endblock %}
{% block content %}
{% include "app/partials/navbar.html" with user=user active_tab='home'%}
<section id="profile" class="f-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 col-sm-10 col-md-6 col-lg-4">
                <div id="profile-details" class="profileBox">
                    <div class="profilePic row justify-content-center">
                        <div class="col-5 col-sm-5 col-md-6 col-lg-6">
                            <img src="{{profile_data.profile_pic.url}}" class="rounded-circle img-fluid userimg mx-auto d-block"
                                alt="...">
                        </div>
                    </div>
                    <div class="details">
                        {% if profile_data.admin %}
                        <div class="row justify-content-center ">
                            <h5 class="fullname verified">{{profile_data.user.first_name}}
                                {{profile_data.user.last_name}} <i class='bx bxs-badge-check'></i></h5>
                        </div>
                        {% else %}
                        <div class="row justify-content-center ">
                            <h5 class="fullname">{{profile_data.user.first_name}} {{profile_data.user.last_name}} </h5>
                             </div> 
                        {% endif %}
                        <div class="row justify-content-center ">
                            <h6 class="username">@{{profile_data.user.username}}</h6>
                        </div>
                        {% if profile_data.user_bio %}
                            <div class="row no-gutters">
                                <p class="col bio">{{profile_data.user_bio}}</p>
                            </div>
                        {% endif %}
                        <div class="col">
                            <small class="row membersince">MemberSince</small>
                            <div class="row membersince">
                                <small>{{profile_data.user.date_joined|date:'b d Y'|capfirst}}</small>
                            </div>
                        </div>
                    </div>   
                </div>
                <div class="options">
                    
                    <div class="row no-gutters justify-content-center">
                        {% if profile_data.user != user %}
                        <div class="col text-center">
                            <a href="{% url 'app:follow' username=profile_data.user.username %}" class="btn w-75 btn-outline-primary">
                                {% if user_follow == True %}
                                Following <i class='bx bx-check'></i>
                                {% else %}
                                Follow
                                {% endif %}
                            </a>
                        </div>
                        <div class="col text-center">
                            <a href="{% url 'app:chat_room' username=profile_data.user.username %}" class="btn w-75 btn-outline-primary">Message</a>
                        </div>
                        {% else %}
                        <div class="col">
                            <a href="{% url 'app:profile_edit' %}" class="btn w-100 btn-outline-primary">Edit Profile</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-10 col-sm-10 col-md-6 col-lg-8">
                <div id="feed-content">
                    {% include "app/partials/user_feed.html" %}
                    
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/app/room.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Message:
{% if user != object.first %}
@{{object.first.username}}
{% else %}
@{{object.second.username}}
{% endif %}
{% endblock %}
{% block description %}Instant or Direct Message to User{% endblock %}
{% block vendor %}
<link rel="stylesheet" href="{% static 'css/room.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/room.js' %}"></script>
{% endblock %}
{% block content %}
<input type="hidden" id="loggedUser" value="{{user.username}}">
{% include "app/partials/navbar.html" with user=user active_tab='message'%}
<section id="room" class="f-section">
    <div class="row justify-content-center">
        <div class="col col-sm-10 col-md-8 col-lg-6">
            <div class="chatbox">
                <div class="user_info row no-gutters">
                    <div class="col ">

                        {% if user != object.first %}
                        <div class="row justify-content-center">
                            <div class="user_pic">
                                <a href="{% url 'app:user_profile' username=object.first.username %}">
                                    <img src="{{object.first.userprofile.profile_pic.url}}"
                                        class="rounded-circle img-fluid mx-auto d-block userimg" alt="...">
                                </a>
                            </div>
                        </div>
                        {% else %}
                        <div class="row justify-content-center">
                            <div class="user_pic">
                                <a href="{% url 'app:user_profile' username=object.second.username %}">
                                    <img src="{{object.second.userprofile.profile_pic.url}}"
                                        class="rounded-circle img-fluid mx-auto d-block userimg" alt="...">
                                </a>
                            </div>
                        </div>
                        {% endif %}

                        {% if user != object.first %}
                        <div class="row no-gutters text-center">
                            <div class="w-100">
                                <h4 class="user_fname d-block">
                                    <a href="{% url 'app:user_profile' username=object.first.username %}">
                                        {{object.first.first_name}} {{object.first.last_name}}
                                        {% if object.first.userprofile.admin %}
                                        <i class='bx bxs-badge-check'></i>
                                        {% endif %}
                                    </a></h4>
                            </div>
                            <div class="w-100">
                                <small class="user_username d-block"><a
                                        href="{% url 'app:user_profile' username=object.first.username %}">@{{object.first.username}}</a></small>
                            </div>
                        </div>
                        {% else %}
                        <div class="row no-gutters text-center">
                            <div class="w-100">
                                <h4 class="user_fname d-block">
                                    <a href="{% url 'app:user_profile' username=object.second.username %}">
                                        {{object.second.first_name}} {{object.second.last_name}}
                                        {% if object.second.userprofile.admin %}
                                        <i class='bx bxs-badge-check'></i>
                                        {% endif %}
                                    </a></h4>
                            </div>
                            <div class="w-100">
                                <small class="user_username d-block"><a
                                        href="{% url 'app:user_profile' username=object.second.username %}">@{{object.second.username}}</a></small>
                            </div>

                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="chat_msg">
                    <div id="chat-items" class="col">
                        {% for chat in object.chatmessage_set.all %}
                        {% if chat.user == user %}
                        <div class="row justify-content-end">
                            {{ chat.user.first_name }} {{ chat.user.last_name }}
                        </div>
                        <div class="row justify-content-end">
                            <li class="chatbubble sent">{{ chat.message }}</li>
                        </div>
                        {% else %}
                        <div class="row justify-content-start">
                            {{ chat.user.first_name }} {{ chat.user.last_name }}
                        </div>
                        <div class="row justify-content-start">
                            <li class="chatbubble recieve">{{ chat.message }}</li>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <form id="form" method="POST">
                    {% csrf_token %}
                    <div class="inputmsg row no-gutters">
                        <div class="col">
                            <input  placeholder="Message" type="text" class="msgarea"
                                name="message" maxlength="280" required=""
                                id="{{form.message.id_for_label}}">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-primary sendicon"><i
                                    class='bx bx-send'></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        var loggedUser = "{{user.username}}";
        console.log("room.js")
        console.log(window.location)
        var loc = window.location
        const formData = $("#form")
        const msgInput = $("#id_message")
        var chatli = $("#chat-items")
        var wsStart = "ws://";
        if (loc.protocol == "https:") {
            wsStart = "wss://";
        }
        var endpoint = wsStart + loc.host + "/ws" + loc.pathname;
        console.log(endpoint);

        const socket = new WebSocket(endpoint);

        socket.onmessage = function (e) {
            console.log("message", e);
            var recieveMsg = JSON.parse(e.data)
            console.log(recieveMsg)
            console.log(loggedUser)
            if (recieveMsg.username == loggedUser) {
                chatli.append(
                    "<div class=\"row justify-content-end\">"
                    + recieveMsg.first_name + ' ' + recieveMsg.last_name
                    + "</div>" +
                    "<div class=\"row justify-content-end\">"
                    + "<li class=\"chatbubble sent\">"
                    + recieveMsg.message
                    + "</li>"
                    + "</div>")
            } else {
                chatli.append(
                    "<div class=\"row justify-content-start\">"
                    + recieveMsg.first_name + ' ' + recieveMsg.last_name
                    + "</div>" +
                    "<div class=\"row justify-content-start\">"
                    + "<li class=\"chatbubble recieve\">"
                    + recieveMsg.message
                    + "</li>"
                    + "</div>")
            }

        };


        socket.onopen = function (e) {
            console.log("open", e);
            formData.submit(function (event) {
                event.preventDefault()
                var msgTxt = msgInput.val()
                console.log(msgTxt)
                msgDict = {
                    'message': msgTxt
                }
                socket.send(JSON.stringify(msgDict))
                msgInput.val('')
            })
        };

        socket.onerror = function (e) {
            console.log("error", e);
        };

        socket.onclose = function (e) {
            console.log("close", e);
        };
    </script>

</section>

{% endblock %}