CS490/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views


app_name = 'app'  # here for namespacing of urls.

urlpatterns = [
    path('', views.index, name="index"),
    path('test', views.test_page, name="testpage"),

    # sign up
    path('signup', views.user_signup, name="signup"),
    path('signup/success', views.user_signup_success, name="signup-success"),

    # login logout
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

    # feed
    path('feed', views.feed, name="feed"),
    path('post/<int:post>', views.user_post, name="user_post"),

    # getfeed
    path('user/search', views.user_search, name="user_search"),
    path('user/feed', views.user_feed, name="user_feed"),

    # profile
    path('profile', views.profile, name="profile"),
    path('profile/edit', views.edit_profile, name="profile_edit"),
    path('user/<str:username>', views.user_profile, name="user_profile"),

    # messages
    path('message', views.msgthread, name="message"),
    path('message/search', views.msg_user, name="msguser"),
    path('message/<str:username>/', views.ThreadView.as_view(), name='chat_room'),

    #follow
    path('follow/<str:username>/', views.follow, name='follow'),

    #like
    path('post/like', views.like_ajax, name='like_ajax'),

    #password change
    path('password', views.change_password, name='password_change'),
]

templates/app/partials/footer.html
<section id="footer" class="footer">
    <div class="row justify-content-center">
    <div class="col-10 footer-info">
      <small>CS-490 Project @NJIT</small>
    </div>
    <div class="col-10 footer-info">
        <small><a href="https://github.com/gajeraYash/app-cs490">Github</a></small>
    </div>
  </div>
</section>

templates/app/partials/msg_user.html
{% if user_results %}
{% for user in user_results %}
<div id='searchresults' class="searchresults cube-trans">
    <div class="row">
        <div class="d-inline-block px-2">
            <a href="{% url 'app:chat_room' username=user.username %}">
                <img src="{{user.userprofile.profile_pic.url}}"
                    class="rounded-circle img-fluid mx-auto d-block userimg" alt="...">
            </a>
        </div>
        <div class="col">
            <div class="row">
                <a href="{% url 'app:chat_room' username=user.username %}">
                    {% if user.userprofile.admin %}
                    <div class="name d-inline-block">{{ user.first_name}} {{user.last_name}} <i
                            class='bx bxs-badge-check'></i> </div>
                    {% else %}
                    <div class="name d-inline-block">{{ user.first_name}} {{user.last_name}}</div>
                    {% endif %}
                </a>
                <a href="{% url 'app:chat_room' username=user.username %}">
                    <div class="username d-inline-block"><span> @</span>{{ user.username }} </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

templates/app/partials/navbar.html
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
        aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button> 
    <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:feed' %}"><i class='bx bxs-home'></i> Home</a>
            <!--s
                  <li class="row no-gutters justify-content-right"></li>
                 <li id="searchfield" class="col">
                     <input id="user-input" class="form-control" type="search" placeholder="Message" aria-label="Message">
                     <li id="search-content">
                     </li>-->
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
                <a class="nav-link waves-effect waves-light">1
                    <i class="fas fa-envelope"></i>
                </a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link message" href ="{% url 'app:message' %}"><i class='bx bx-chat'></i> Message</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    <i class='bx bxs-user'></i> {{user.first_name}} {{user.last_name}}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item" href="{% url 'app:profile' %}"><i class='bx bxs-user-detail'></i> My Profile</a>
                  <a class="dropdown-item" href="{% url 'app:password_change' %}"><i class='bx bxs-wrench'></i> Change Password</a>
                  <a class="dropdown-item" href="{% url 'app:logout' %}"><i class='bx bx-log-out'></i> Log out</a>
                </div>
              </li>
        </ul>
    </div>
</nav>

templates/app/partials/user_feed.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/feed.css' %}" type="text/css" media="screen">
<!--icons link-->
{% if user_feed %}
{% for feed in user_feed %}
<div id="post" class="post">
    <div class="row no-gutters">
        <div class="user_pic">
            <a href="{% url 'app:user_profile' username=feed.user.username %}">
                <img src="{{feed.user.userprofile.profile_pic.url}}"
                    class="rounded-circle img-fluid mx-auto d-block sizeoption" alt="...">
            </a>
        </div>
        <div class="col user_post">
            <div class="user_info">
                
                <a href="{% url 'app:user_profile' username=feed.user.username %}">
                    <div class="name">{{feed.user.first_name}} {{feed.user.last_name}}
                        {% if feed.user.userprofile.admin %} 
                        <i class='bx bxs-badge-check'></i></div>
                        {% endif %}
                </a>
                <a href="{% url 'app:user_profile' username=feed.user.username %}">
                    <div class="username">@{{feed.user.username}}</div>
                </a>
            </div>
            <div class="announcement">{{ feed.announcement|safe }}</div>
            {%if feed.image %}
            <div class="userfile">
                <img src="{{feed.image.url}}" class="img-fluid mx-auto d-block imgoption" alt="...">
            </div>
            {% endif %}
            <div class="row comment no-gutters justify-content-center">
                <div class="col">
                    <a href="javascript:;" onclick="like('{{feed.id}}')" >
                        {% if feed.id in liked %}
                        <div name="{{feed.id}}" class="post-icons likecall d-inline"><i class='bx bxs-like'></i></div>
                        {% else %}
                        <div name="{{feed.id}}" class="post-icons likecall d-inline"><i class='bx bx-like'></i></div>
                        {% endif %}
                        <div class="d-inline">Like</div>
                        {% for post in like_count %}
                            {% if post == feed %}
                                {{post.num_likes}}
                            {% endif %}
                        {% endfor %}
                    </a>
                </div>
                <div class="col">
                    <a  href="{%url 'app:user_post' post=feed.id%}">
                        <div class="post-icons d-inline"><i class='bx bx-comment-detail'></i></div>
                        <div class="d-inline">Comment</div>
                    </a>
                </div>
                <div class="col">
                    <div class="date">{{ feed.created }}</div>
                </div>
            </div>

        </div>
    </div>
</div>
</div>
{% endfor %}

{% endif %}

templates/app/partials/user_search.html
{% if user_results %}
{% for user in user_results %}
<div id='searchresults' class="searchresults cube-trans">
    <div class="row">
        <div class="d-inline-block px-2">
            <a href="{% url 'app:user_profile' username=user.username %}">
                <img src="{{user.userprofile.profile_pic.url}}"
                    class="rounded-circle img-fluid mx-auto d-block userimg sizeoption" alt="...">
            </a>
        </div>
        <div class="col">
            <div class="row">
                <a href="{% url 'app:user_profile' username=user.username %}">
                    {% if user.userprofile.admin %}
                    <div class="name d-inline-block">{{ user.first_name}} {{user.last_name}} <i
                            class='bx bxs-badge-check'></i> </div>
                    {% else %}
                    <div class="name d-inline-block">{{ user.first_name}} {{user.last_name}}</div>
                    {% endif %}
                </a>
            </div>
            <div class="row">
                <a href="{% url 'app:user_profile' username=user.username %}">
                    <div class="username d-inline-block"><span>@</span>{{ user.username }} </div>
                </a>
            </div>
        </div>
    </div>

</div>
{% endfor %}
{% endif %}